### ISSUE TITLE
Suggestions for Doc Edits pt. 2

### ISSUE THREAD

**Issue by MDTerps** [GenesysGo/docs-shadow-cloud#68]
This covers the following pages of the documentation:
Learn
DAGGER
Design
On-Chain Proofs
Smart Contracts
Compute
FAQ
[SHDW Docs Suggestion pt. 2.docx](https://github.com/GenesysGo/docs-shadow-cloud/files/11175689/SHDW.Docs.Suggestion.pt.2.docx)

**Comment by GummersGG** [comment]
done. thanks!
